<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<IsPackable>false</IsPackable>
		<AssemblyName>ProjectFollowUp.BFF.WebApi.IntegrationTests</AssemblyName>
		<RootNamespace>ProjectFollowUp.BFF.WebApi.IntegrationTests</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" />
		<PackageReference Include="FluentValidation" />
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="Shouldly" />
		<PackageReference Include="Testcontainers.KurrentDb" />
		<PackageReference Include="Testcontainers.MongoDb" />
		<PackageReference Include="Testcontainers.RabbitMq" />
		<PackageReference Include="TestStack.BDDfy" />
		<PackageReference Include="xunit" />
		<PackageReference Include="xunit.runner.visualstudio">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>


	<ItemGroup>
		<Using Include="Shouldly" />
		<Using Include="TestStack.BDDfy" />
		<Using Include="Xunit" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\src\RabbitMqSetup\RabbitMqSetup.csproj" />
		<ProjectReference Include="..\..\src\WebApi\WebApi.csproj" />
	</ItemGroup>

</Project>