<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
		<AssemblyName>ProjectFollowUp.BFF.Domain</AssemblyName>
		<RootNamespace>ProjectFollowUp.BFF.Domain</RootNamespace>
  </PropertyGroup>

</Project>
