services:
  keycloaksetup.projectfollowup.local:
    image: project-follow-up/keycloaksetup:local
    container_name: keycloaksetup.projectfollowup.local
    hostname: keycloaksetup.projectfollowup.local
    restart: no
    environment:
      - SetupSettings__keycloakBaseUrl=http://keycloak.projectfollowup.local:8080
      - SetupSettings__masterAdminUserName=admin
      - SetupSettings__masterAdminPassword=admin
      - SetupSettings__projectFollowUpRealm__uiClient__redirectUrls__0=https://localhost:5000/*
      - SetupSettings__projectFollowUpRealm__uiClient__webOrigins__0=https://localhost:5000
      - SetupSettings__projectFollowUpRealm__adminUser__username=projectfollowup
      - SetupSettings__projectFollowUpRealm__adminUser__password=projectfollowup
      - keycloak.projectfollowup.local
    networks:
      - auth-network
      - monitoring-network
    profiles:
      - setup

  rabbitmqsetup.projectfollowup.local:
    image: project-follow-up/rabbitmqsetup:local
    container_name: rabbitmqsetup.projectfollowup.local
    hostname: rabbitmqsetup.projectfollowup.local
    restart: no
    environment:
      - SetupSettings__RabbitMqRestUrl=http://rabbitmq.projectfollowup.local:15672
      - SetupSettings__RabbitMqRestUsername=admin
      - SetupSettings__RabbitMqRestPassword=admin
    depends_on:
      - rabbitmq.projectfollowup.local
    networks:
      - auth-network
      - monitoring-network
    profiles:
      - setup

  webapisetup.projectfollowup.local:
    image: project-follow-up/webapisetup:local
    container_name: webapisetup.projectfollowup.local
    hostname: webapisetup.projectfollowup.local
    restart: no
    environment:
      - Keycloak__baseAddress=http://keycloak.projectfollowup.local:8080
      - Keycloak__clientSecret=6znFAwHjTmR2MGG1vFbLaGGMsb5VhXdn
      - Keycloak__validIssuer=https://localhost:5000/auth/realms/project-follow-up
      - Kurrent__ConnectionString=esdb://kurrent.projectfollowup.local:2113?tls=false
    depends_on:
      - kurrent.projectfollowup.local
      - keycloak.projectfollowup.local
    networks:
      - auth-network
      - monitoring-network
    profiles:
      - setup
