<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
		<AssemblyName>ProjectFollowUp.BFF.Infrastructure</AssemblyName>
		<RootNamespace>ProjectFollowUp.BFF.Infrastructure</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="EventSourcing\Kurrent\ProjectionsProcessing\ProjectsList.js" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="EventSourcing\Kurrent\ProjectionsProcessing\Projects.js" />
    <EmbeddedResource Include="EventSourcing\Kurrent\ProjectionsProcessing\ProjectsList.js" />
    <EmbeddedResource Include="EventSourcing\Kurrent\ProjectionsProcessing\Users.js" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Keycloak.Net.Core" />
    <PackageReference Include="KurrentDB.Client" />
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
  </ItemGroup>

</Project>
